[meta]
name        = "DiscordNotify"
author      = "Geiler_Hengst69"
category    = "Utilities"
version     = "0.2.2"
siteid      = 524

[script]
dependencies = [ "NadeoServices" ]
optional_dependencies = [ "ChampionMedals", "Discord" ]
