[meta]
name        = "DiscordNotify"
author      = "Geiler_Hengst69"
category    = "Utilities"
version     = "0.2.2"
siteid      = 524

[script]
dependencies = [ "NadeoServices" ]
optional_dependencies = [ "ChampionMedals", "Discord" ]
shared_exports = [ 
    "src/SharedExport/Discord/AllowedMentions.as"
    , "src/SharedExport/Discord/AllowedMentionType.as"
    , "src/SharedExport/Discord/Author.as"
    , "src/SharedExport/Discord/Base.as"
    , "src/SharedExport/Discord/Embed.as"
    , "src/SharedExport/Discord/EmbedField.as"
    , "src/SharedExport/Discord/Footer.as"
    , "src/SharedExport/Discord/Media.as"
    , "src/SharedExport/Discord/Message.as"
    , "src/SharedExport/Discord/MessageFlags.as"
    , "src/SharedExport/Discord/Provider.as"
    , "src/SharedExport/Discord/Role.as"
    , "src/SharedExport/Discord/Snowflake.as"
    , "src/SharedExport/Discord/User.as"
    , "src/SharedExport/Discord/Webhook.as"
    , "src/SharedExport/Discord/WebhookMessage.as"
    , "src/SharedExport/Discord/WebhookResponse.as"
    ]
module = "DiscordNotify"
