[meta]
name        = "WebHook"
author      = "Geiler_Hengst69"
category    = "Utilities"
version     = "0.1.1"

[script]
dependencies = [ "NadeoServices" ]
optional_dependencies = [ "ChampionMedals", "Discord" ]
