name: Bug Report
description: Use this to report any bugs you encountered using this plugin.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Describe how we can make this bug happen ourselves.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please check the log for errors. Copy and paste any error messages about this plugin.
      render: shell
  - type: textarea
    id: other-info
    attributes:
      label: Additional Information
      description: "Leave any other relevant comments here."
